version: '2'

services:
  o2ipam:
    depends_on:
      - db
    links:
      - db:db
    image: o2ipam
    #image: pvrmza/o2ipam
    restart: always
    env_file:
      - .env_o2ipam    

volumes:
  db_data:
  
